#!/bin/bash

### BEGIN INIT INFO
# Provides:          mongod
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mongod service
# Description:       MongoDB SysV service, useful when Systemd is not available
### END INIT INFO

process_spec="--user mongodb --pidfile /run/mongod-sysv.pid"

case "$1" in
	status)
		echo "Checking status of mongod..."
		start-stop-daemon --status $process_spec
		result=$?
		if [ "$result" = 0 ]; then
			echo "mongod is running."
		else
			echo "mongod is not running ($result)."
		fi
		exit "$result"
		;;
	start)
		echo "Starting mongod..."
		# Did not work: --notify-await
		start-stop-daemon --start --oknodo $process_spec \
			--chuid mongodb:mongodb --make-pidfile --background \
			--startas /usr/bin/mongod \
			-- --config /etc/mongod.conf

		echo -n "Waiting for localhost:27017..."
		while ! nc -z localhost 27017; do
			echo -n "."
			sleep 0.1
		done
		echo " OK."
		;;
	stop)
		echo "Stopping mongod..."
		start-stop-daemon --stop --oknodo $process_spec \
			 --remove-pidfile --retry 5
		echo "OK."
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {status|start|stop|restart}"
		exit 1
		;;
esac

exit 0
